wildfires/main/routes.py
from flask import render_template, request, Blueprint, redirect, url_for, flash
from flask_login import login_user, LoginManager, current_user, logout_user, login_required
from wildfires.main.forms import SearchForm, LoginForm, RegisterForm
from flask_googlemaps import Map
from flask_cors import CORS, cross_origin
from wildfires.models import Fire, NWCGUnit, Users
from sqlalchemy import text
from wildfires import login_manager, db
from flask_bcrypt import Bcrypt, generate_password_hash, check_password_hash

main = Blueprint("main", __name__)

# login_manager = LoginManager()
# login_manager.init_app(app)
# login_manager.login_view = 'login'
#


@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(user_id)

@main.route("/", methods=["GET", "POST"])
@main.route("/login", methods=["GET", "POST"])
# @cross_origin()
def login():
    form = LoginForm()
    csrf_token = form.csrf_token
    if form.validate_on_submit():
        print("Post Method")
        # data = request.get_json()
        # print("request")
        user = Users.query.filter_by(username=form.username.data).first()
        print("User: ", user)
        print(form.password.data)
        check = check_password_hash(user.password, form.password.data)
        print(check)
        if user is None or not check:
            flash('Invalid username or password', 'error')
            return redirect(url_for('main.login'))
        login_user(user)
        return redirect(url_for('main.home', form=form, csrf_token=csrf_token))
    else:
        return render_template('login.html', form=form)

# @main.route("/", methods=["GET", "POST"])
@main.route("/home", methods=["GET", "POST"])
@cross_origin()
@login_required
def home():    
    form = SearchForm()
    if form.validate_on_submit():
        startYear = form.startYear.data
        endYear = form.endYear.data
        state = form.state.data
        rows = form.rows.data
        sort = form.sort.data
        order = form.order.data
        
        return redirect(url_for('main.searchHome', page=1, startYear=startYear, endYear=endYear, state=state, rows=rows, sort=sort, order=order))
    return render_template("home.html", user = current_user.name, form=form)



@main.route("/search/<sort>/<order>", methods=["GET", "POST"])
@cross_origin()
def searchHome(sort, order, state='', startYear=1992, endYear=1992, rows=1, page=1):    
    form = SearchForm()
    state = request.args.get('state', '', type=str)
    page = request.args.get('page', 1, type=int)
    rows = request.args.get('rows', 1, type=int)
    startYear = request.args.get('startYear', 1992, type=int)
    endYear = request.args.get('endYear', 1992, type=int)

    if(len(state) < 1):
        fires = Fire.query.filter((Fire.FIRE_YEAR >= startYear), (Fire.FIRE_YEAR <= endYear)).order_by(text(f'{sort} {order}')).paginate(page=page, per_page=rows)
    else:
        fires = Fire.query.filter((Fire.FIRE_YEAR >= startYear), (Fire.FIRE_YEAR <= endYear), (Fire.STATE == state)).order_by(text(f'{sort} {order}')).paginate(page=page, per_page=rows)
    markers = []
    for fire in fires.items:
        markers.append({
                            'icon': '/static/icons/fire_icon.png',
                            'lat':  fire.LATITUDE,
                            'lng':  fire.LONGITUDE,
                            'infobox': f"ID: {fire.FPA_ID} | Name: {fire.FIRE_NAME} | SIZE: {fire.FIRE_SIZE} | Cause: {fire.STAT_CAUSE_DESCR}"
                        })
    return render_template("search.html", form=form, fires=fires, markers=markers, startYear=startYear, endYear=endYear, rows=rows, state=state, sort=sort, order=order)


@main.route("/fire/<ID>", methods=["GET", "POST"])
@cross_origin()
def fire(ID):    
    fire = Fire.query.filter((Fire.FPA_ID == ID)).first()
    NWCG_Unit = NWCGUnit.query.filter((NWCGUnit.UnitId == fire.NWCG_REPORTING_UNIT_ID)).first()
    Lat = fire.LATITUDE
    Long = fire.LONGITUDE
    markers =   [{
                    'icon': '/static/icons/fire_icon.png',
                    'lat':  Lat,
                    'lng':  Long,
                    'infobox': f"ID: {fire.FPA_ID} | Name: {fire.FIRE_NAME} | SIZE: {fire.FIRE_SIZE} | Cause: {fire.STAT_CAUSE_DESCR}"
                }]
    return render_template("fire.html", fire=fire, markers=markers, NWCG_Unit=NWCG_Unit, Lat=Lat, Long=Long)



@main.route("/about")
def about():
    return render_template("about.html", title="About")


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, 10)
        new_user = Users(username=form.username.data, name=form.name.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('main.login'))

    return render_template('register.html', form=form)

wildfires/templates/about.html
{% extends "layout.html" %}
{% block content %}
<body>
    <!-- Main -->
    <section :style="{ backgroundImage: 'url(' + require('../assets/images/background.jpg') + ')' }">
      <div class="container items-center">

        <!-- Content -->
        <div class="flex flex-1 flex-col items-center lg:pl-2">

          <!-- Welcome -->
          <h1 class="text-navy font-medium text-3xl  text-center mt-8 mb-2">
            About
          </h1>
          <p class="text-navy font-medium text-md text-center mb-5">
            
          </p>
            
        </div>
    </div>
    </section>
    <!-- Who am I -->
    <section class="py-20">

      <!-- Header -->
      <div class="w-3/4 lg:w-5/12 mx-auto px-2">
        <h2 class="text-3xl text-center text-navy">How to use this site?</h2>
        <p class="text-center text-md text-gray-500 mt-4 mb-5">
            This is a wildfire database project for CSE106: Exploratory Computing (AKA Full-Stack Development).            
        </p>
      </div>
    </section
  </body>
{% endblock content %}

wildfires/templates/fire.html
{% extends "layout.html" %}
{% block content %}

{% set LAT = Lat %}
{% set LONG = Long %}

<div class="d-flex flex-rows justify-content-center mb-5">
  {{ googlemap(
      identifier="test-map",
          lat=LAT,
          lng=LONG,
      zoom=8,
      style="display: flex;flex-direction: rows;flex-grow:1;height:calc(100vh - 100px);width:calc(100vw - 100px);margin:0;",
      maptype='TERRAIN',
      zoom_control=false,
      streetview_control=false,
      fullscreen_control=false,
      maptype_control=false,
      mapdisplay=flase,
      collapsible=false,
      scale_control=false,
      center_on_user_location=false,
      markers=markers
      ) }}
</div>

<div class="mb-5">
  <h4>Fire Info</h4>
  <table data" class="table table-striped">
    <thead>
        <tr>
        <th >ID</th>
        <th >Name</th>
        <th >Size</th>
        <th >Size Class</th>
        <th >Cause Code</th>
        <th >Cause</th>
        <th >Reporting Unit</th>
        <th >Year</th>
        <th >State</th>
        </tr>
    </thead>
    <tbody>
      <tr>
          <td>{{fire.FPA_ID}}</td>
          <td>{{fire.FIRE_NAME}}</td>
          <td>{{fire.FIRE_SIZE}} Acres</td>
          <td>{{fire.FIRE_SIZE_CLASS}}</td>
          <td>{{fire.STAT_CAUSE_CODE}}</td>
          <td>{{fire.STAT_CAUSE_DESCR}}</td>
          <td>{{fire.SOURCE_REPORTING_UNIT_NAME}}</td>
          <td>{{fire.FIRE_YEAR}}</td>
          <td>{{fire.STATE}}</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="mb-5">
  <h4>NWCG Unit Info</h4>
  <table data2" class="table table-striped">
    <thead>
        <tr>
        <th >ID</th>
        <th >Name</th>
        <th >GACC</th>
        <th >Wildland Role</th>
        <th >Unit Type</th>
        <th >Department</th>
        <th >Country</th>
        <th >State</th>
        </tr>
    </thead>
    <tbody>
      <tr>
          <td>{{ NWCG_Unit.UnitId }}</td>
          <td>{{NWCG_Unit.Name}}</td>
          <td>{{NWCG_Unit.Gacc}}</td>
          <td>{{NWCG_Unit.WildlandRole}}</td>
          <td>{{NWCG_Unit.UnitType}}</td>
          <td>{{NWCG_Unit.Department}}</td>
          <td>{{NWCG_Unit.Country}}</td>
          <td>{{NWCG_Unit.State}}</td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock content %}

wildfires/templates/home.html
{% extends "layout.html" %}
{% block content %}
<h1 class="text-center mb-5">Welcome to the Wildfire Database {{user}}</h1>

<div class="content-section mb-5"> 
     <form method="POST" action=""> <!-- State -->
         {{ form.hidden_tag() }}
         <fieldset class="formgroup">
             <div class="form-group">
                {{ form.startYear.label(class="mb-0") }}
                {{ form.startYear(class="form-control form-control-md mb-3") }}  

                {{ form.endYear.label(class="mb-0") }}
                {{ form.endYear(class="form-control form-control-md mb-3") }}

                {{ form.state.label(class="mb-0") }}
                {{ form.state(class="form-control form-control-md mb-3") }}

                {{ form.rows.label(class="mb-0") }}
                {{ form.rows(class="form-control form-control-md mb-3") }} 

                {{ form.sort.label(class="mb-0") }}
                {{ form.sort(class="form-control form-control-md mb-3") }} 

                {{ form.order.label(class="mb-0") }}
                {{ form.order(class="form-control form-control-md mb-3") }} 

             </div>
         </fieldset>
         <div class="form-group">
            {{ form.submit(class="btn btn-outline-dark ") }}
       </div>
     </form>
</div> 
{% endblock content %}

wildfires/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Wildfires | {{ title }}</title>
    {% else %}
        <title>Wildfires</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-navy fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Wildfires</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
              </div>
            </div>
          </div>
        </nav>
      </header>

        <div class="row d-flex justify-content-center">
          <div class="col-md-8">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
              {% endwith %}
            {% block content %}{% endblock %}
          </div>
        </div>
        
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 
</body>
</html>

wildfires/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}"> -->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}" >
    <title>Login</title>
</head>
<body>
    <h1>Login Page</h1>
	{% if error %}
		<p>{{ error }}</p>
	{% endif %}
	<form id="login" action="{{ url_for('main.login') }}" method="POST">
		<label>Username:</label>
		<input type="text" name="username"><br>
		<label>Password:</label>
		<input type="password" name="password"><br>
		<input type="submit" value="Login" >
		<input type="hidden" name="csrf_token"  value="{{ csrf_token() }}" >
		{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
				{% for category, message in messages %}
				<div class="alert alert-{{ category }}">
					{{ message }}
				</div>
				{% endfor %}
			{% endif %}
		{% endwith %}
	</form>

	<!-- Optional JQuery/Styling -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</body>
</html>

wildfires/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}"> -->
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}" >
    <title>Register</title>
</head>
<body>
    <h1>Register Page</h1>
	{% if error %}
		<p>{{ error }}</p>
	{% endif %}
	<form id="register" action="{{ url_for('main.register') }}" method="POST">
        {{ form.hidden_tag() }}
        {{ form.username }}
		{{	form.name  }}
        {{ form.password }}
        {{ form.submit }}
			<input type="hidden" name="csrf_token"  value="{{ csrf_token() }}" >
		{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages %}
				{% for category, message in messages %}
				<div class="alert alert-{{ category }}">
					{{ message }}
				</div>
				{% endfor %}
			{% endif %}
		{% endwith %}
    </form>

	<!-- Optional JQuery/Styling -->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

wildfires/templates/search.html
{% extends "layout.html" %}
{% block content %}

{% if fires %}
<div class="d-flex flex-rows justify-content-center mb-5">
    {{ googlemap(
        identifier="test-map",
            lat=39.8283,
            lng=-98.5795,
        zoom=4,
        style="display: flex;flex-direction: rows;flex-grow:1;height:calc(100vh - 100px);width:calc(100vw - 100px);margin:0;",
        maptype='TERRAIN',
        zoom_control=false,
        streetview_control=false,
        fullscreen_control=false,
        maptype_control=false,
        mapdisplay=flase,
        collapsible=false,
        scale_control=false,
        center_on_user_location=false,
        markers=markers
        ) }}
</div>

<table id="data" class="table table-striped">
    <thead>
        <tr>
        <th id="ID">ID</th>
        <th id="Name">Name</th>
        <th id="Size">Size</th>
        <th id="Cause">Cause</th>
        <th id="Year">Year</th>
        <th id="State">State</th>
        </tr>
    </thead>
    <tbody>
        {% for fire in fires.items %}
            <tr>
                <td><a href="{{ url_for('main.fire', ID=fire.FPA_ID )  }}">{{fire.FPA_ID}}</a></td>
                <td>{{fire.FIRE_NAME}}</td>
                <td>{{fire.FIRE_SIZE}} Acres</td>
                <td>{{fire.STAT_CAUSE_DESCR}}</td>
                <td>{{fire.FIRE_YEAR}}</td>
                <td>{{fire.STATE}}</td>
            </tr>

        {% endfor %}
    </tbody>
</table>


{% set minYear = startYear %}
{% set maxYear = endYear %}
{% set numRows = rows %}
{% set State = state %}
{% set Sort = sort %}
{% set Order = order %}


  <!-- Pagination Links-->
<div class="text-right">
    <a href="{{ url_for('main.searchHome', page=fires.prev_num,  startYear=minYear, endYear=maxYear, state=State, rows=numRows, sort=Sort, order=Order )  }}"
       class="btn btn-outline-dark 
       {% if fires.page == 1 %}disabled{% endif %}">
        &laquo;
    </a><!-- Loop through the number of pages to display a link for each-->
    {% for page_num in fires.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}{% if page_num %}
<!-- Check for the active page and set the link to "Active"-->
            {% if fires.page == page_num %}
            <a href="{{ url_for('main.searchHome', page=page_num, startYear=minYear, endYear=maxYear, state=State, rows=numRows, sort=Sort, order=Order )  }}"
               class="btn btn-dark">
                {{ page_num }}
            </a>
            {% else %}
            <a href="{{ url_for('main.searchHome', page=page_num, startYear=minYear, endYear=maxYear, state=State, rows=numRows, sort=Sort, order=Order )   }}"
               class="btn btn-outline-dark">
                {{ page_num }}
            </a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}    <a href="{{ url_for('main.searchHome', page=fires.next_num, startYear=minYear, endYear=maxYear, state=State, rows=numRows, sort=Sort, order=Order )  }}"
       class="btn btn-outline-dark 
       {% if fires.page == fires.pages %}disabled{% endif %}">
        &raquo;
    </a>
</div>
<p class="text-right mt-3">
   Showing page {{ fires.page }} of {{ fires.pages }}
</p>
{% endif %}

{% endblock content %}